Auth submit
pyatl/podium-django pull request #41
Opened 2017-08-17 18:24 UTC by jacques-cadet

2017-08-18 01:13 UTC, jbonzo commented
Since this PR is based off of #40 I added a WIP label for clarity.

2017-08-18 02:23 UTC, jacques-cadet commented
Not based off of, just should be done first. Why create a link to
registeration when it doesn't exist?

On Aug 17, 2017 9:13 PM, "Ricky Barillas" <notifications@github.com> wrote:

Since this PR is based off of #40
<https://github.com/pyatl/podium-django/pull/40> I added a WIP label for
clarity.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pyatl/podium-django/pull/41#issuecomment-323234009>,
or mute
the thread
<https://github.com/notifications/unsubscribe-auth/ATx8wg6R2t7x5r3DY9Oeqk4IvbGxTE0fks5sZOUlgaJpZM4O6ooB>
.

2017-08-18 02:24 UTC, jbonzo commented on podium/talks/templates/talks/submit.html
> +				<br>
In regards to the link tag for Register, where should the link go? Or is the registration page not yet completed?

2017-08-18 02:26 UTC, jbonzo commented
Well I said based off of since the first commit in this PR is the commit for the other PR. Also I'm a little confused by your other message. Was that a reply to my comment regarding the registration link?

2017-08-18 02:28 UTC, jacques-cadet commented
Registration update is in PR #40, it includes all necessary code.

On Aug 17, 2017 10:24 PM, "Ricky Barillas" <notifications@github.com> wrote:

> *@jbonzo* commented on this pull request.
> ------------------------------
>
> In podium/talks/templates/talks/submit.html
> <https://github.com/pyatl/podium-django/pull/41#discussion_r133863314>:
>
> >  			</form>
> +
> +			{%else%}
> +
> +				
> +				<h4 style="font-size: 30px;text-align:center;color: #005580; text-shadow: 0 0 50px #669996; ">A verified email is required to submit a talk propasal, and you must be logged in. <br> Please <a href="">Register</a> or <a href="{% url 'auth_login'%}">Login</a>.</h4>
> +				<br>
>
> In regards to the link tag for Register, where should the link go? Or is
> the registration page not yet completed?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pyatl/podium-django/pull/41#pullrequestreview-57093535>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ATx8wsqZj_iK-W2SSYTI-iKfIyv8bPAkks5sZPXIgaJpZM4O6ooB>
> .
>

2017-08-18 02:33 UTC, jbonzo commented
Right. I think we have a slight misunderstanding but I will wait to review this PR anymore until #40 is merged.

2017-08-18 03:17 UTC, jacques-cadet commented
Was that a reply to my comment regarding the registration link?

No, It's my reason for making the initial comment, just in question form. 
Nothing personal.

In regards to the link tag for Register, where should the link go? Or is the registration page not yet completed?

Registration update is in PR #40, it includes all necessary code, links and all.
Sorry for the confusion.

2017-09-07 23:47 UTC, jrrickerson requested changes
Please update from upstream and resolve the conflicts with your other PR and update your branch, and I should be able to review and merge this shortly.

2017-09-08 13:57 UTC, closed without merging

2017-09-08 13:58 UTC, jacques-cadet commented
Closed to correct conflicts.